name: Deploy Logic App

on:
  workflow_dispatch:  # Allows manual triggering
    inputs:
        name:
          type: choice
          description: Stage to deploy to
          options: 
          - dev
          - test
          - main

jobs:
  prepare-and-deploy:
    name: Read Appsettings
    runs-on: ubuntu-latest
    outputs:
      appsettings-json: ${{ steps.read_appsettings.outputs.appsettings_json }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.name }}

      - name: Read and encode appsettings.json
        id: read_appsettings
        run: |
          appsettings=$(cat iac/parameters.dev.json | base64 -w 0)
          echo "appsettings_json=${appsettings}" >> $GITHUB_OUTPUT

  call-workflow-passing-data:
    name: Deploy Logic App
    needs: prepare-and-deploy
    uses: L-Quibiq/master/.github/workflows/logic-app-deployment.yml@main
    with:
      appsettings-json: ${{ needs.prepare-and-deploy.outputs.appsettings-json }}
    secrets: inherit
