name: Update Workflows from Central Repo

on:
  workflow_call:

jobs:
  update-workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Master Repository
        uses: actions/checkout@v3
        with:
          ref: main  # Check out the main branch
          fetch-depth: 0  # Full history for force push

      - name: List contents of directory 1
        run: ls -R

      - name: Fetch from Central Repo
        run: |
          git remote add central https://github.com/L-Quibiq/Master.git
          git fetch central main

      - name: List contents of directory 2
        run: ls -R

      - name: Copy Workflows
        run: |
          rm -rf .github/workflows/*
          cp -R Master/starter-workflows/* .github/workflows/
          git add .github/workflows/
          git commit -m "Update workflows from central repo"
          git push --force
